#!/bin/bash

service=$1
port=$2
first_port=$port
hostname=$3
current_hostname=$hostname
protocol=$4
filepath=$5

FIS=$IFS
IFS=$' & '

crtpath="servers/server/crt"
datapath="servers/server/data"
keypath="servers/server/key"

privatekey_percert=`grep privatekey:percert info`
privatekey_copy=`grep privatekey:copy info`
privatekey="server"

permissions=400

#inst = instruction, value = value
while read -r inst value; do
	if [ "$value" ]; then
		case $inst in
			"value")
				if [[ "$value" == "inc" ]]; then
					temp=`cat tmp/value`
					(( temp++ ))
					echo $temp > tmp/value || exit 1
				else
					echo $value > tmp/value
				fi
				;;
			"server")
				#set server name
				server=$service"_"$value
				;;
			"msg")
				#set message
				msg=$value
				;;
			"status")				#if connected, is it good?, bad?, what?
				status=$value
				;;
			"set_crt")
				#set cert (name)
				crt=$value
				if [[ privatekey_percert ]]; then
					privatekey=$crt
				fi
				;;
			"create_crt")

				#create signing request
				if [[ "$value" != "no_change" ]]; then		#voidaan asettaa crt samalla kun se tehdään
					if [[ "$value" == "hostname" ]]; then
						crt=$current_hostname
					else
						crt=$value
					fi
					if [[ privatekey_percert ]]; then
						privatekey=$crt
						if [[ "$privatekey_copy" ]]; then
							openssl genrsa -out tmp/key/$privatekey.key 2048
							chmod $permissions tmp/key/$privatekey.key
							cp tmp/key/$privatekey.key $keypath/$privatekey.key
						else
							openssl genrsa -out $keypath/$privatekey.key 2048
							chmod $permissions $keypath/$privatekey.key
						fi
					fi
				fi

				#create crts from root ca if root ca created???

				#create crt into tmp dir

				echo "subjectAltName = DNS:*.$san, DNS:$san" > tmp/server.ext
				#IdenTrust
				openssl req -new -key $keypath/$privatekey.key -out tmp/server.csr -subj "/C=FI/ST=Oulu/L=Oulu/O=ouspg/OU=ouspg/CN=$cn"
				chmod $permissions tmp/server.csr
				#create certificate
				openssl x509 -req -days $days -in tmp/server.csr -signkey $keypath/$privatekey.key -out tmp/certs/trytls_$crt.crt -extfile tmp/server.ext
				chmod $permissions tmp/certs/trytls_$crt.crt

				#mkdir -p "$crtpath/"$crt
				cp tmp/certs/trytls_$crt.crt "$crtpath"/"$crt".crt

				;;
			"ssl_protocols")
				#set $proto
				proto=$value
				;;
			"ssl_ciphers")
				#set $ciph
				ciph=$value
				;;
			"days")
				#set days, if days = 0, use firstday, lastday
				days=$value
				;;
			"set_current_hostname_cat")
				if [[ "$value" == "hostname" ]]; then
					value=$hostname
				fi
				current_hostname="$value`cat tmp/value`"	#e.g: 222.222.222. + 2
				;;
			"set_current_hostname")
				if [[ "$value" == "hostname" ]]; then
					current_hostname=$hostname
				else
					current_hostname=$value
				fi
				;;
			"host")
				#set common name
				if [[ "$value" == "hostname" ]]; then
					san=$current_hostname
					cn=$current_hostname
				else
					san=$value
					cn=$value
				fi
				;;
			"san")
				if [[ "$value" == "hostname" ]]; then
					san=$current_hostname
				else
					san=$value
				fi
				;;
			"cn")
				if [[ "$value" == "hostname" ]]; then
					cn=$current_hostname
				else
					cn=$value
				fi
				;;
			"push")

				if [[ "$value" != "no_change" ]]; then		#voidaan asettaa crt samalla kun se tehdään
					if [[ "$value" == "hostname" ]]; then
						crt=$current_hostname
					else
						crt=$value
					fi
					if [[ "$privatekey_percert" ]]; then
						privatekey=$crt
					fi
				fi

				{ echo -e "server: servers/$server\n\tport: $port using $crt.crt" ;
				  echo -e "\tprotocols: $proto ciphers: $ciph" ; } | tee -a tmp/server_info

				mkdir -p "$datapath/"$server
				echo $msg > "$datapath/"$server/index.html

				echo "$port & $msg & $status & trytls_$crt.crt & $current_hostname" >> tmp/conf	|| exit 3

				if [[ "$protocol" == "https" ]]; then

					#DEFAULT CONF

					{ echo "" ; echo "# $server " ; \
					echo 'server {' ; \
					echo "	listen $port;" ; \

					echo '	ssl on; ' ; \
					echo "	ssl_certificate $crtpath/$crt.crt; " ; \
					echo "	ssl_certificate_key $keypath/$privatekey.key;" ;\

					echo '	location $keypath/ { ' ;\
					echo '	  deny all; ' ;\
					echo '	  return 403; ' ;\
					echo '	} ' ;\

					echo "	root $datapath/$server/;" ;\
					echo '	index index.html;' ;\

					echo "	ssl_protocols       $proto" ;\
					echo "	ssl_ciphers         $ciph" ;\

					echo '	server_name trytls;' ;\

					echo '	location / {' ;\
					echo '		try_files $uri $uri/ /index.html;' ;\
					echo '	}' ;\
					echo '}' ; } >> servers/default.conf || exit 3
				fi

				(( port++ ))


				;;
		esac
	fi
done <"$filepath"

IFS=$FIS

echo $port > tmp/port || exit 4
