#!/bin/bash

hostname=$1		#e.g. localhost
from=$2
to=$3

#bash curl_test localhost <first port> <last port>
#bash curl_test localhost $(((`cat tmp/port_first`  + 3))) $(cat tmp/port)

if [ "$#" -lt 3 ]; then
	echo "Usage: $0 <hostname> port_first port_last>" 
	exit 1
fi

for (( port=$from; port<=$to; port++ )); do
	#just for protocol checking, no cert check needed in this case
	curl https://$hostname:$port -ks

done
