#!/bin/bash

stubspath=$1

#create conf-default file concatting the files wanted


#create default conf (" conf1 conf2"), Hox the spaces, currently backends

FIS=$IFS
IFS=':'       #'anything' but ' '

rm shared/simplerunner/conf/default >> /dev/null 2>&1
echo $2 | sed -e 's/ / shared\/simplerunner\/conf\//g' | xargs cat \
  >>shared/simplerunner/conf/default

IFS=FIS

shift 2 #stubspath + confs

#create stubs file(s)

echo $stubspath

#remove old files
rm shared/simplerunner/stubs/* >> /dev/null 2>&1

#init docker-compose
{ echo "version: '2'"; echo 'services:'; } > docker-compose.yml || exit 2

while [ $# -gt 0 ]; do

  language=$1

  FIS=$IFS
  IFS='&'

  read -a drivers <<< "${language}"
  size="${#drivers[@]}"

  for i in "${!drivers[@]}"
  do driver="${drivers[$i]}"

    if [[ $i == 0 ]]; then
      #get stubs (first driver is the "language")
      echo `find $stubspath/  -type d -name "$driver"-* -printf "%f\n" >> shared/simplerunner/stubs/$driver.stubs`
      if [[ $size != 1 ]]; then
        continue
      fi
    fi

    echo $driver

    { echo " $driver:" ;\
    echo "  build: drivers/$driver" ;\
    echo "  container_name: bashtls_$driver" ; \
    echo "  volumes: " ; \
    echo "  - ./shared:/etc/shared" ;\
    echo "  - $stubspath:/etc/shared/stubs" ;
    echo '  network_mode: "host" ' ; }\
    >> docker-compose.yml || exit 4

  done

  IFS=FIS

  #edit docker-compose.yml

  shift 1

done

#Todo: add better support for running only wanted stubs + more drivers
