#!/bin/bash

exit_safe()
{
  IFS=FIS;
  exit $1

}

stubspath=$1
#stubs=$2,$3,$4,$5,$6,...

#create tmp folder:
  #create files for languages that include the stubs to be run

sharedpath="data/shared"
tmppath=$sharedpath"/tmp"

#remove old tmp path (could be made optional, or parts of it)

rm $tmppath -R >>  /dev/null 2>&1
mkdir $tmppath -p

FIS=$IFS
IFS=$'-'

echo "starting out ......................................"

shift 1   #stubspath

while [ $# -gt 0 ]; do

  echo $stub

  stub=$stubspath"/"$1

  #get language(before '-')
  #language=?

  #write stub

  echo $stub

  $stub >> $tmppath"/"$language || exit_safe 1 #no can do

done

exit_safe
