#!/bin/bash

port=$1
hostname=$2

echo "port: $port"
echo -e "hostname: $hostname\n"

if [ "$#" -lt 3 ]; then
	#do nothing
	echo "wrong number of arguments (" "$#" "given), at least 3 needed"
	echo "port = port of the first server, service = name of the service in the data/ directory"
	echo "..."
	echo "correct would be: init port hostname service1 service2 ... serviceN"	
	echo "..."	
	exit 1
fi

exit_safe()
{
	#rm tmp -R
	exit $1
}

begin_init()
{
	rm tmp -R >> /dev/null 2>&1
	mkdir -p tmp/certs >> /dev/null 2>&1

	sudo touch tmp/port
	sudo openssl genrsa -out tmp/server.key 2048
}

begin_init

shift 2		# port + hostname

while [ $# -gt 0 ]; do

	service=$1

	#delete old files

	rm $service -R >> /dev/null 2>&1

	#create new files
	
	sudo bash configs/create "$service" "$port" "$hostname" || exit_safe $?

	port=`sudo cat tmp/port`

	shift	

done

exit_safe 0
	
#TODO: exits, etc..

