#!/bin/bash

port=$1
hostname=$2
protocol=$3

echo "port: $port"
echo -e "hostname: $hostname\n"

if [ "$#" -lt 4 ]; then
	#do nothing
	echo "wrong number of arguments (" "$#" "given), at least 3 needed"
	echo "port = port of the first server, service = name of the service in the data/ directory, protocol = data/dir name"
	echo "..."
	echo "correct would be: init port hostname https service1 service2 ... serviceN"	
	echo "..."
	exit 1
fi

exit_safe()
{
	#rm tmp -R
	exit $1
}

begin_init()
{
	rm tmp -R >> /dev/null 2>&1
	mkdir -p tmp/certs >> /dev/null 2>&1

	touch tmp/port
	echo $port > tmp/port_first

	#create privatekey

	openssl genrsa -out tmp/server.key 2048
	
	

}

begin_init

shift 3		# port + hostname + protocol

while [ $# -gt 0 ]; do

	service=$1

	#delete old files

	rm $service -R >> /dev/null 2>&1

	#create new files
	
	bash configs/create "$service" "$port" "$hostname" "$protocol" || exit_safe $?

	port=`cat tmp/port`

	shift	

done

#write all certs into tmp/certs/certs.info

for f in tmp/certs/*; do
	echo ${f##*/} >> tmp/certs/certs.info
done




exit_safe 0
	
#TODO: exits, etc..
