#!/bin/bash

# <command> <stub(file)> <conf> <ca> <curpath> <stub(printable name)> <timeout>


#init-------------------------------------------------------------
curpath=$0
if [[ ! $curpath == \/* ]]; then
  curpath=${curpath#./}         ##remove ./
  curpath=`pwd`/$curpath  ##add .../..
fi

if [[ $curpath =~ "/"  ]]; then
  curpath=${curpath%/*}   ##remove /run..
else
  curpath=""
fi
command=$1
#execcommand='exec'
if [[ $command == "_" ]]; then
  command=""
  extracommand='./'
fi


filename=$2
if [[ ! $filename =~ '/' ]]; then
  if [[ $filename =~ ":" ]]; then
    path=${filename%:*}
    cd $curpath"/../../../../stubs/$path"
    filename=${filename##*:}
  else
    cd $curpath"/../../../../stubs/$filename"
    filename=`find -name "[Rr]un*"`' Run run'
  fi
  filename=${filename##*/}
fi

status=""
for f in echo $filename #| tr " " "\n"
do
  if [[ `$command $extracommand''$f 2>&1 | grep "UNSUPPORTED"` ]]; then
    filename=$f #this is propably the correct file, if that is not the case, well then you will see some errors
    status="ok"
    break
  fi
done
if [[ ! $status ]]; then  #no correct file found or might be wrong command?
  exit 1
fi

confpath=$3
if [[ ! $confpath =~ '/' ]]; then
  confpath=$curpath"/conf/"$confpath
fi

certspath=$4
if [[ "$certspath" ]]; then
  if [[ "$certspath" != '_' ]]; then
    if [[ $certspath == "--" ]]; then
      certspath=$curpath/certs
    else
      certspath=${certspath//[[:blank:]]/}
    fi
  else
    certspath=""
  fi
  if [[ "$5" ]]; then
    if [[ $5 != "_" ]]; then
      curpath=$5
    fi
  fi
fi

stub=$6
if [[ ! $stub ]]; then
  stub="${filename##*\/}"
fi
filepath=${curpath%/*}

timeout=$7
if [[ ! $timeout ]]; then
  timeout=15
fi

#read info
infopath=$curpath/info
if [[ -f "$infopath/info" ]]; then
  info=`cat $infopath/info`
  parallel=`echo $info | grep 'parallel'`
  printerror=`echo $info | grep 'print-error'`
fi

#functions-------------------------------------------------------------

#echo timeout: $timeout

handleresponse()
{
  #echo "hello world"
  start=0
  process=$1
  while [[ $process ]]; do

    if ps -p $process >> /dev/null 2>&1
    then
      (( start++ ))
      sleep 1
      if [[  $start -gt $timeout ]]; then
        kill $process >> /dev/null 2>&1
        echo "TIMED OUT"
        return
      fi
    else
      return
    fi
  done

}

connect()
{
  port=$1
  status=$2
  crt=$3
  hostname=$4

  if [[ "$crt" == "certs/test.crt" ]]; then
    response=`$command $extracommand''$filename $hostname $port "$curpath"/"$crt" 2>&1 & handleresponse $!`
    #status="OK?"
  elif [[ "$crt" == "_" ]]; then
    if [[ "$certspath" =~ "." ]]; then
      response=`$command $extracommand''$filename $hostname $port "$certspath"  2>&1 & handleresponse $!`
    else
      response=`$command $extracommand''$filename $hostname "$port"  2>&1 & handleresponse $!`
    fi
  elif [[ "$certspath" ]]; then
    if [[ "$certspath" != "-k" ]]; then
      #echo $command $filename $hostname $port "$certspath"/"$crt"
      response=`$command $extracommand''$filename $hostname $port "$certspath"/"$crt" 2>&1 & handleresponse $!`
      #status="OK?"
    else
      response=`$command $extracommand''$filename $hostname $port "$certspath"  2>&1 & handleresponse $!`
      #kill $!
      #status="OK?"
    fi
  else
    response=`  $command $extracommand''$filename $hostname "$port"  2>&1 & handleresponse $!`
  fi

  #choose color

  if [[ "$response" == "UNSUPPORTED" ]]; then
    color='\e[0;37m'    #allright
    response='[ OK?  ][ UNSUPPORTED  ]'
    #msg=$filename
  elif [[ "$response" == "TIMED OUT" ]]; then
    color='\e[0;40m'      #most likely the connection was succesfull, but can be sure
    response="[      ][  TIMED OUT   ]"
  elif [[ "$status" == "BAD" ]]; then

    if [[ "$response" == "VERIFY FAILURE" ]]; then
      color='\e[0;32m'    #green, success
      response='[ PASS ]'[$response]
    else
      color='\e[0;41m'    #red, failure(either error or verify did succeed)
      if [[ "$response" == "VERIFY SUCCESS" || $printerror ]]; then
        response='[ FAIL ]'[$response]
      else
        if [[ ! $printerror ]]; then
          response='[ ERROR]'
        fi
      fi
    fi

  elif [[ "$status" == "GOOD" ]]; then

    if [[ "$response" == "VERIFY SUCCESS" ]]; then
      color='\e[0;36m'    #green, success
      response="[ PASS ][$response]"
    else
      if [[ "$response" == "VERIFY FAILURE" || $printerror ]]; then
        color='\e[0;41m'    #red, failure(either error or verify did not succeed)
        response="[ FAIL ][$response]"
      else
        if [[ ! $printerror ]]; then
          response='[ ERROR]'
        fi
      fi
    fi
  else
    color='\e[0;37m'    #allright
    if [[ "$response" == "VERIFY SUCCESS" || "$response" == "VERIFY FAILURE" ]]; then
      response="[ OK?  ][$response]"
    else
      if [[ ! $printerror ]]; then
        response="[ ERROR]"
      fi
    fi
  fi

  echo -e "$color[$stub]$response[$msg]\e[0m[$hostname]"

}

#main-------------------------------------------------------------

FIS=$IFS
IFS='&'

while read -r port msg status crt hostname; do

  port=${port//[[:blank:]]/}
  #msg=${msg//[[:blank:]]/}
  status=${status//[[:blank:]]/}
  crt=${crt//[[:blank:]]/}
  hostname=${hostname//[[:blank:]]/}

  #echo "port: " .$port.
  #echo "msg: " .$msg.
  #echo "crt: " .$crt.
  #echo "status: " .$status.
  #echo "hostname: " .$hostname.
  #echo $filename
  #echo $confpath
  #echo $certspath

  #try to connect

  if [[ $parallel ]]; then
    connect $port $status $crt $hostname &
  else
    connect $port $status $crt $hostname
  fi

done < "$confpath"


IFS=$FIS

exit 0
