#!/bin/bash

#cp sr ../bin/        "install"

if [[ $1 ]]; then
  if [[ $1 == "--help" ]]; then
    echo "usage: sr <certspath> <command> <run-path> <stub> <backends>"
    echo "for more info: https://github.com/ouspg/trytls/tree/master/runners/bashtls/shared/simplerunner"
    exit 0
  fi
  certspath=$1
else
  certspath='--'
fi

if [[ $2 && $2 != '--' ]]; then
  command=$2
else
  command="python&mono&python3&java&bash&_&go run"
fi

if [[ $3 && $3 != '--' ]]; then
  path=$3
else
  path="../trytls/runners/bashtls/shared/simplerunner"
fi

stub=$4
if [[ ! $stub || $stub == '--' ]]; then
  stub=`pwd`
  stub=${stub##*/}
elif [[ ! $stub =~ ":" ]]; then
  if [[ ! $stub =~ "/" ]]; then
    tmp=`pwd`
    tmp=${tmp##*/}
    stub=$tmp:$stub
  fi
fi

if [[ $5 && $5 != '--' ]]; then
  confs=$5
else
  confs="ssllabs&badssl-all&others" #you can add your own backends here
fi

#set settings ----------------------------------------------------------
if [[ $certspath == "settings" ]]; then
  bash $path/settings $2
  exit 0
fi

curpath='_'
IFS="&"

#run tests ------------------------------------------------------------
path=$path/run
for cmd in $command; do       #find correct command(s)
  #echo $cmd
  for conf in $confs; do      #try against all the confs
    bash $path $cmd $stub $conf $certspath $curpath $stub || break      #if first conf fails(== wrong command or file(for the command)), next command
  done
done
