#!/bin/bash

#cp sr ../bin/        "install"

if [[ $1 && $1 != '--' ]]; then
  command=$1
else
  command="python&mono&python3&java&bash&_&go run"
fi

if [[ $2 && $2 != '--' ]]; then
  path=$2
else
  path="../trytls/runners/bashtls/shared/simplerunner/run"
fi

stub=$3
if [[ ! $stub || $stub == '--' ]]; then
  stub=`pwd`
  stub=${stub##*/}
elif [[ ! $stub =~ ":" ]]; then
  if [[ ! $stub =~ "/" ]]; then
    tmp=`pwd`
    tmp=${tmp##*/}
    stub=$tmp:$stub
  fi
fi

if [[ $4 && $4 != '--' ]]; then
  confs=$4
else
  confs="ssllabs&badssl-all&others" #you can add your own backends here
fi

if [[ $5 ]]; then
  certspath=$5
else
  certspath='--'
fi

curpath='_'

IFS="&"

for cmd in $command; do       #find correct command
  #echo $cmd
  for conf in $confs; do      #try against all the confs
    bash $path $cmd $stub $conf $certspath $curpath $stub || break      #if first conf fails(== wrong command or file(for the command)), next command
  done
done
