#!/bin/bash

host=$1		#e.g. localhost
port=$2
ca_bundle=$3

if [ "$#" -lt 2 ]; then
	echo "UNSUPPORTED"
	exit 1
fi

status=0

if [[ "$ca_bundle" ]]; then
	#-servername chrismeller.com
	resp=`echo "Q" | openssl s_client -CAfile $ca_bundle -servername $host -connect $host:$port 2>&1`
else
	resp=`echo "Q" | openssl s_client -servername $host -connect $host:$port 2>&1`
fi

#echo $resp

if echo "$resp" | grep -q "Verify return code:"; then
	if echo "$resp" | grep -q "Verify return code: 0 (ok)"; then
		echo "VERIFY SUCCESS"
	else
		echo "VERIFY FAILURE"
	fi
	exit 0
fi

echo $resp
exit 1
