#!/bin/bash

if [ "$#" -ne 3 ]; then
	#do nothing
	echo "wrong number of arguments (" "$#" "given)"
	echo "name = service name, port = port for the first server, hostname ≃ CN"
	echo "..."
	echo "correct would be: create name port hostname"	
	echo "..."	
	exit 1
fi

service=$1
port=$2
hostname=$3


if [[ $service != "initialize" ]]; then

	#make directories
	mkdir $service
	mkdir $service/server


	#initialize Docker-file
				
	{ echo 'FROM nginx:1.9.7'; \

	echo 'ADD default.conf /etc/nginx/conf.d/'; \
	echo 'ADD server/server.key /etc/nginx/server/server.key'; } > $service/Dockerfile || exit 1

else
	#initialize docker-compose	

	{ echo "version: '2'"; echo 'services:'; } > docker-compose.yml || exit 2
fi

#create other files, servers, certs, osv.., jne.., etc..
sudo bash configs/create_servers "$service" "$port" "$hostname" "configs/data/$service"

exit 0

#TODO: more clear + exits ok
