FROM debian:latest

RUN apt-get update
RUN apt-get install -y python
RUN apt-get install -y python-pip
RUN apt-get install -y git
RUN apt-get install -y python3-requests python-requests
RUN pip install trytls
RUN git clone https://github.com/ouspg/trytls.git
