#!/usr/bin/env escript
%% -*- erlang -*-

%% trytls (https://github.com/ouspg/trytls) stub for erlang

%% Uncomment the following line if needed. Hard to say if compiling is worthwhile here.
%% -mode(compile).


%%does not check certificates (at least for now)
main([Url, Port]) ->
    start_deps(),
    Result = httpc:request("https://" ++ Url ++ ":" ++ Port),
    check(Result);

%%does check certificates
main([Url, Port, CaFile]) ->
    start_deps(),
    Result = httpc:request(head, {"https://" ++ Url ++ ":" ++ Port, []},
        [{ssl,[{verify, 2}, {depth, 2}, {ssl_imp, new},
        {fail_if_no_peer_cert, true},
        {cacertfile, CaFile}]}], []),
    check(Result);

main(_) ->
    usage(),
    halt(1).

usage() ->
    io:format("usage: run <domain> <port> [ca_file]~n"),
    io:format("Will do request as: https://<domain>:<port>~n").

start_deps() ->
    inets:start(),
    ssl:start().

check({ok, _}) ->
    io:format("ACCEPT~n");

check({error, {_,[_, {_,_,{tls_alert, _}}]}}) ->
    io:format("REJECT~n");

check({error, Reason}) ->
    io:format(user, "~p~n", [Reason]),
    halt(1).
