#!/bin/bash

stub=$1
stubspath="/stubs"
newstubspath="/compiled"

filepath=$stubspath/$stub/Run.java

if [[ ! -f $filepath ]]; then
  echo "No such file or directory: $filepath"
  exit 1
fi

#copy

mkdir $newstubspath >> /dev/null 2>&1
cp $stubspath/$stub $newstubspath/$stub -R

#compile

cd $newstubspath/$stub
javac Run.java >> /dev/null 2>&1
if [[ ! $? ]]; then
  exit 1
fi

echo $newstubspath  #set new stubspath (run:->resp->stubspath->sr->run(with new stubspath))

exit 0
