#!/bin/bash

host=$1		#e.g. localhost
port=$2
ca_bundle=$3

if [ "$#" -lt 2 ]; then
	echo "UNSUPPORTED"
	exit 1
fi

status=0

if [[ "$ca_bundle" ]]; then
	if [[ "$ca_bundle" == "-k" ]]; then
		curl https://$host:$port -k >> /dev/null 2>&1 || status=$?
	else
		curl --cacert $ca_bundle https://$host:$port >> /dev/null 2>&1 || status=$?
	fi
else
	curl https://$host:$port >> /dev/null 2>&1 || status=$?
fi

if [[ "$status" -eq 0 ]]; then
	echo "VERIFY ACCEPT"
	exit 0
else
	#CURLE_UNSUPPORTED_PROTOCOL=1		#if some of these not needed -> can be removed
	#CURLE_SSL_CONNECT_ERROR=35
	#CURLE_PEER_FAILED_VERIFICATION=51
	#CURLE_SSL_CERTPROBLEM=58
	#CURLE_SSL_CIPHER=59
	#CURLE_SSL_CACERT=60
	#CURLE_RECV_ERROR=56, The TLS connection was non-properly terminated i.a. in trytls-runner localhost test, error better?.

	error="1 35 51 58 59 60"
	for i in $error; do
		if [[ $status -eq $i ]]; then
			echo "VERIFY REJECT"
			exit 0
		fi
	done
fi
echo "Error code: $status, for more info: https://curl.haxx.se/libcurl/c/libcurl-errors.html"
exit $status
